services:
  web:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5174:5174"     # Vite
    environment:
      CHOKIDAR_USEPOLLING: "true"      # WSL/Windows: mejor detecci칩n
      WATCHPACK_POLLING: "true"
      DOCKER_ENV: "true"               # Indica que est치 ejecut치ndose en Docker
      BACKEND_IP: ${BACKEND_IP:-172.21.0.4}
      # VITE_API_URL: "http://localhost:8080"  # ej. para tu backend
    volumes:
      - ./:/app
      - /app/node_modules   # volumen an칩nimo para no pisar node_modules
    networks:
      - apirest-tiendaderopa_app-net  # Conectar a la red real del backend
    command: sh -c "npm install && npm run dev -- --host"

networks:
  apirest-tiendaderopa_app-net:
    external: true          # Usar la red existente del backend
